## Pytorch Tensors and Numpy

Numpy is a popular scientific Python numerical computing library. And because of that Numpy is so popular Pytorch is able to interact with Numpy
Example:
* Data starts out in Numpy and the data is wanted to be used in Pytorch data for deep learning purposes 
* torch.from_numpy(ndarray) 
* There is also a function that converts a pytorch tensor to a numpy tensor --> 'torch.Tensor.numpy()'
- Numpy Default Data Type: float64
- Pytorch Default Data Type: float32

In [45]:
import torch
import numpy as np

In [46]:
# Numpy array to tensor

array = np.arange(1.0, 8.0)

tensor = torch.from_numpy(array) # creating the tensor in Pytorch by using the array created using Numpy

array, tensor, array.dtype

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64),
 dtype('float64'))

In [47]:
torch.arange(1.0, 8.0).dtype

# Numpy default data type is f64, while pytorch default data type is f32, so creating a tensor in pytorch using numpy will reflect the default data type from Numpy(f64)

torch.float32

In [48]:
# in order to change the data type to f32 we have to specify the type when creating the pytorch tensor using the type function

tensor2 = torch.from_numpy(array).type(torch.float32)
tensor2

tensor([1., 2., 3., 4., 5., 6., 7.])

In [49]:
# changing values of the array --> what happens to the pytorch tensor?

array = array + 1

array, tensor
# here it is shown that changing the original array will not change the tensor as the memory of the tensor is stored in another place
# meaning that they don't share any memory

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [50]:
# Going from Pytorch tensor to Numpy array 

tensor = torch.ones(7)

numpyTensor = tensor.numpy()

tensor, numpyTensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [51]:
numpyTensor.dtype

# the array reflects the data type from the copied over tensor

dtype('float32')

In [52]:
# What happens to the numpy array when the pytorch tensor has been changed?

tensor = tensor + 1

tensor, numpyTensor

# here it is shown that changing the original tensor will not change the array as the memory of the array is stored in another place
# meaning that they don't share any memory

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
# further practice: https://pytorch.org/tutorials/beginner/examples_tensor/polynomial_numpy.html