# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [5]:
# Import torch
import torch

# Create random tensor
tensor2 = torch.rand(7, 7)
tensor2

tensor([[0.6867, 0.0913, 0.4315, 0.7370, 0.4735, 0.6844, 0.8356],
        [0.7852, 0.2533, 0.3185, 0.8745, 0.1218, 0.5352, 0.9912],
        [0.6864, 0.7954, 0.3822, 0.6824, 0.9911, 0.6074, 0.8731],
        [0.6358, 0.8316, 0.3729, 0.5734, 0.8287, 0.0765, 0.6212],
        [0.2376, 0.8287, 0.3137, 0.3143, 0.0771, 0.1828, 0.3712],
        [0.0886, 0.2252, 0.4496, 0.7525, 0.2627, 0.3085, 0.7535],
        [0.9849, 0.6223, 0.9461, 0.4289, 0.2938, 0.1570, 0.6841]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [12]:
# Create another random tensor
tensor3 = torch.rand(1, 7)

# Perform matrix multiplication 
torch.mm(tensor2, tensor3.T)

tensor([[2.2951],
        [2.0775],
        [2.7227],
        [2.0321],
        [1.1828],
        [1.3456],
        [2.4923]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [13]:
# Set manual seed
manualSeed = 0

# Create two random tensors
torch.manual_seed(manualSeed)
randTensor4a = torch.rand(7, 7)

torch.manual_seed(manualSeed)
randTensor4b = torch.rand(1, 7)

# Matrix multiply tensors
torch.mm(randTensor4a, randTensor4b.T)

tensor([[1.5985],
        [1.1173],
        [1.2741],
        [1.6838],
        [0.8279],
        [1.0347],
        [1.2498]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [21]:
# Set random seed on the GPU
randSeedGPU = 1234

torch.cuda.manual_seed(randSeedGPU)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [25]:
# Set random seed
torch.cuda.manual_seed(1234)

# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"

# Create two random tensors on GPU
randTensor6a = torch.rand(2, 3).cuda()

torch.cuda.manual_seed(1234)
randTensor6b = torch.rand(2, 3).cuda()

print(randTensor6a, randTensor6b)

tensor([[0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051]], device='cuda:0') tensor([[0.9320, 0.1759, 0.2698],
        [0.1507, 0.0317, 0.2081]], device='cuda:0')



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [27]:
# Perform matmul on tensor_A and tensor_B
matrixMul = torch.mm(randTensor6a, randTensor6b.T)

print(matrixMul, matrixMul.shape)

tensor([[0.6927, 0.1211],
        [0.3206, 0.1033]], device='cuda:0') torch.Size([2, 2])


### 8. Find the maximum and minimum values of the output of 7.

In [29]:
# Find max
max = torch.max(matrixMul)

# Find min
min = torch.min(matrixMul)

print(max, min)

tensor(0.6927, device='cuda:0') tensor(0.1033, device='cuda:0')


### 9. Find the maximum and minimum index values of the output of 7.

In [30]:
# Find arg max
indexMax = torch.argmax(matrixMul)

# Find arg min
indexMin = torch.argmin(matrixMul)

print(indexMax, indexMin)

tensor(0, device='cuda:0') tensor(3, device='cuda:0')



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [36]:
# Set seed
randSeed = 7
torch.manual_seed(randSeed)

# Create random tensor
randTensor10a = torch.rand(1, 1, 1, 10)

# Remove single dimensions
randTensor10b = randTensor10a.squeeze()

# Print out tensors and their shapes
print(randTensor10a, randTensor10a.shape)
print()
print(randTensor10b, randTensor10b.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])

tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
