### Matrix Multiplication

Two main ways to perform multiplication in neural networks and deep learning

1. Element-wise multiplication
2. Matrix Multiplication (Dot Product)

Two main rules for performing matrix multiplication needs to satisfy:
1. The **inner dimensions** must match (very literal --> refers to the elements that are in the center)
    - `(3, 2) @ (3, 2)` won't work: as the inner dimensions(2, and 3) don't match (last element in the first tensor, and the first element in the second tensor)
    - `(2, 3) @ (3, 2)` will work:
    - `(3, 2) @ (2, 3)` will work:
2. The resulting matrix has the shape of the **outer dimensions**
    - `(2, 3) @ (3, 2)` --> `(2, 2)`
    - `(3,2) @ (2, 3)` --> `(3, 3)`
 

Inner Dimensions:
- (2, `3`) @ (`3`, 2)

Outer Dimensions:
- (`2`, 3) @ (3, `2`)

In [1]:
import torch # type: ignore

In [12]:
# Element wise multiplication

tensor = torch.tensor([1, 2, 3])
tensor

tensor([1, 2, 3])

In [13]:
print(tensor, '*', tensor)
print(f"Equals: {tensor * tensor}")

# the result of multiplying the tensor by itself

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [14]:
# is stored in the torch.matmul function
# mat: matrix
# mul: multiplication

torch.matmul(tensor, tensor)
# gives you the dot product of the tensor
# got to 14 by adding all the elements in the previous tensor: 1 + 4 + 9 = 14

tensor(14)

Matrix Multiplication by hand:

$$
1*1 + 2*2 + 3*3 = 1 + 4 + 9 = 14
$$

In [15]:
%%time

# Comparing the time it takes to multiply a tensor using a for loop versus using the torch function: torch.matmul

# for loop
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]

print(value)

tensor(14)
CPU times: total: 0 ns
Wall time: 1 ms


In [16]:
%%time

# torch.matmul
torch.matmul(tensor, tensor)

# the torch.matmul function is almost 10 times faster than using a for loop, even with only 3 values, as the values and the size of the tensor keeps increasing, the time difference will go up
# exponentially. Always use the torch.matmul function when multiplying tensors

CPU times: total: 0 ns
Wall time: 0 ns


tensor(14)

### Matrix Multiplication: The two main rules of Multiplication

One of the most common errors in deep learning: 
- Shape Errors

In [17]:
# Shapes for matrix multiplication

tensorA = torch.tensor([[1,2],
                       [3,4],
                       [5,6]])

tensorB = torch.tensor([[7, 10],
                       [8, 11],
                       [9, 12]])

torch.mm(tensorA, tensorB) # mm is the same as .matmul

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
tensorA.shape, tensorB.shape
# how to adjust tensors that are not random, and were pre-defined

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix tensor shape issues, it is possible to manupulate the shape of a tensor using transpose

**Transpose** switches the axes or dimenstions of a given tensor

In [19]:
transposedTensorB = tensorB.T # saving the newly transposed tensor to transposedTensorB
transposedTensorB

# tensor.T or tensor.transpose() will transpose the tensor, which means that the rows and columns will switch places

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [20]:
tensorB.T.shape
# the shape of the tensor has now been changed with the dimensions being changed, and now the inner dimenstions of tensorA and tensorB are matching, meaning matrix multiplication is now possible

torch.Size([2, 3])

In [22]:
torch.mm(tensorA, transposedTensorB) 
# now multiplying tensorA by the newly transposed tensorB: transposedTensorB
# it now works as tensorB has no been transposed

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])