### Manipulating Tensors (Tensor operations)

Tensor Operations:
- Addition
- Subtraction
- Multiplication (element-wise)
- Division
- Matrix Multiplication

In [33]:
import torch

In [34]:
# Tensor Addition
# Creating a tensor and adding 10 to it:

tensor = torch.tensor([1, 2, 3])
tensor + 10

# When adding a scalar to a tensor, the scalar is added to each element of the tensor

tensor([11, 12, 13])

In [35]:
# Tensor Multiplication
# Creating a tensor and multiplying it by 10:

tensor * 10
# When multiplying a scalar to a tensor, the scalar is added to each element of the tensor

tensor([10, 20, 30])

In [36]:
tensor
# since the value of the tensor has not been reassigned, it remains the same

tensor([1, 2, 3])

In [37]:
# in order to change the values of the tensor, we have to first reassign the tensor to the new value

tensor = tensor * 10

tensor
# since the value of the tensor has been reassigned, the new value of the tensor is now changed

tensor([10, 20, 30])

In [38]:
# Torch also has a built in function to add and multply tensors

torch.mul(tensor, 10)

tensor([100, 200, 300])

In [39]:
torch.add(tensor, 10)

tensor([20, 30, 40])