## Indexing (Selecting data from Tensors)

Indexing with Pytorch is very similar to indexing with Numpy (and follows the same index as python index: 0 - n-1)

In [2]:
import torch

# First create a tensor to learn indexing on

x = torch.arange(1, 10).reshape(1, 3, 3)

print(x)
print()
print(x.shape)

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

torch.Size([1, 3, 3])


In [3]:
# Testing out indexing on the x tensor

x[0]

# will grab the first bracket from the tensor
# the highest value and only value for the first tensor is 1, as the first dimension is 1
# meaning that it is only possible to index at position 0 (index: 1 - 1 = 0)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [4]:
# indexing on the middle bracket (or when dim = 1)

x[0][0]

# this time it will grab the first row from the middle tensor

tensor([1, 2, 3])

In [5]:
# indexing on the inner most bracket (or the last dimension)

x[0][0][0]
# the first bracket will choose the entire tensor 
# the second bracket chooses an entire row
# and the third bracket chooses the specific element in the row specified in the second bracket

# this time it will return the first element from the first row from the middle tensor

tensor(1)

### Practice in selecting specific elements

In [6]:
# getting the row: [4, 5, 6]
x[0][1]

tensor([4, 5, 6])

In [7]:
# getting the number 8
x[0][2][1]

tensor(8)

In [10]:
# it is also possible to use ":" to select all of a target dimension

# example: selecting all the elements from the first row

x[:, 0]

tensor([[1, 2, 3]])

In [11]:
x[0, :, 2]
# this gives all of the 

tensor([3, 6, 9])

In [12]:
# get all the values of the 0th and 1th dimensions, but only the first index of the second dimension

x[:, :, 1]
# first index or the second value, 

tensor([[2, 5, 8]])

In [22]:
# get all the values of the 0th dimension, but only the 1st index of the 1st and 2nd dimension

x[:, 1, 1], x[0, 1, 1]
# the reason why the first expression has a sqaure bracket is because we are selecting all of the elements while the second expression is only selects the first element

# or selecting the middle tensor

(tensor([5]), tensor(5))

In [24]:
# get index 0 of 0th and 1st dimension and all  the values of 2nd dimension

x[0, 0, :]

tensor([1, 2, 3])

In [26]:
# returning 3, 6, 9

x[:, :, 2]
# need all of the elements in the first and second dimension, and the elements in the second dimension or the last row

tensor([[3, 6, 9]])