### 3. Putting Tensors and Models on the GPU

The reason that models and tensors are wanted on the GPU is because a GPU will result in faster computations. (Tensor Operations)

In [21]:
import numpy
import torch

# Creating a tensor (defaulting on the CPU)

tensor = torch.tensor([1, 2, 3], device = "cpu")

print(tensor, tensor.device) # results in a tensor not on the GPU

tensor([1, 2, 3]) cpu


In [8]:
tensor = torch.tensor([1, 2, 3])

print(tensor, tensor.device) # results in a tensor not on the GPU

# even without specifying, by default the tensor device is set to the CPU

tensor([1, 2, 3]) cpu


In [17]:
# Moving tensor to GPU if available

device = "cuda" if torch.cuda.is_available() else "cpu" # importing over code from lesson 14: setting up GPU/CUDA

tensorOnGPU = tensor.to(device) 
# device moves to any target available, but since a GPU is available, the tensor is now moved to the GPU

tensorOnGPU # now the device for the tensor is set to the GPU

# there might be different tensors stored on different GPU's later on

tensor([1, 2, 3], device='cuda:0')

### 4. Moving tensors back to the CPU
Numpy tensors are only stored on the CPU, so to use those tensors with pytorch they have to be converted back to the CPU to work.

In [18]:
tensorOnGPU.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [26]:
# to fix the GPU numpy issue, the tensor has to be first set back to the CPU

tensorBackOnCPU = tensorOnGPU.cpu().numpy() # with the tensor now on the cpu calling the .numpy() function now works

print(tensorBackOnCPU)

[1 2 3]


In [27]:
tensorOnGPU
# since tensorBackOnCPU has been reasigned, the original tensor remains unchanged

tensor([1, 2, 3], device='cuda:0')