## Reproducibility

Trying the take the random out of random (trying to reproduce the random tensors created for practices in the other lessons)

How a nerual network learns: Starts with random numbers -> tensor operations -> update random numbers to try to make the numbers better representations -> again -> again -> ...

Trying to keep the randomness out: Say that you want to perform an experiment on a tensor, then you would need the same tensor for each new experiment, thus meaning that you woud need the reproduce the same tensor each and every time

In order to reduce the randomness in nerual networks and Pytorch you need the concept of a **random seed**, the seeds flavours the randomness, since computers are not able to truly generate random numbers, so they rely on algorithms to produce the random values

*You can reproduce tensors by using the torch.manual_seed, giving random values that are reproducible*

In [1]:
import torch

In [2]:
torch.rand(3, 3)

tensor([[0.2361, 0.9039, 0.6448],
        [0.9498, 0.7809, 0.7689],
        [0.5577, 0.5174, 0.7577]])

In [3]:
torch.rand(3, 3)

# here as it is shown that even if you call two tensors with the same parmeters they will differ
# but for sharing purposes involving specific numbers then when the recipient receives the file and runs it then they would produce different numbers

tensor([[0.0173, 0.2108, 0.6293],
        [0.3968, 0.5266, 0.2710],
        [0.8094, 0.9916, 0.6165]])

In [4]:
randTensorA = torch.rand(3, 4)
randTensorB = torch.rand(3, 4)

print(randTensorA)
print(randTensorB)
print(randTensorA == randTensorB)

# there are going to be random numbers, and there is a chance for the two tensors to have a same number

tensor([[0.6163, 0.3437, 0.8826, 0.7922],
        [0.8882, 0.3236, 0.7735, 0.5317],
        [0.1059, 0.5687, 0.1686, 0.2991]])
tensor([[0.3773, 0.0064, 0.9183, 0.7919],
        [0.1232, 0.3726, 0.7814, 0.0359],
        [0.1721, 0.9547, 0.2627, 0.8113]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [5]:
# making a random and reproducible tensor

randomSeed = 246

torch.manual_seed(randomSeed) # setting the random seed of the random tensors (or flavour the randomness with a seed)

randTensorC = torch.rand(3, 4)
randTensorD = torch.rand(3, 4)

print(randTensorC)
print(randTensorD)
print(randTensorC == randTensorD)

tensor([[0.7902, 0.9813, 0.5914, 0.3650],
        [0.7470, 0.6896, 0.8815, 0.7708],
        [0.7810, 0.2139, 0.1007, 0.5230]])
tensor([[0.3128, 0.8854, 0.6202, 0.9351],
        [0.4072, 0.3055, 0.3805, 0.4427],
        [0.0846, 0.1081, 0.6236, 0.3008]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [7]:
randomSeed = 246

torch.manual_seed(randomSeed) 
randTensorC = torch.rand(3, 4)

torch.manual_seed(randomSeed) 
randTensorD = torch.rand(3, 4) # set the randomness after each random method is called

# manual seed only works after each method is called, and needs to be called again for each instance that torch.rand is called

print(randTensorC)
print(randTensorD)
print(randTensorC == randTensorD)

tensor([[0.7902, 0.9813, 0.5914, 0.3650],
        [0.7470, 0.6896, 0.8815, 0.7708],
        [0.7810, 0.2139, 0.1007, 0.5230]])
tensor([[0.7902, 0.9813, 0.5914, 0.3650],
        [0.7470, 0.6896, 0.8815, 0.7708],
        [0.7810, 0.2139, 0.1007, 0.5230]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


Extra Resources: *https://pytorch.org/docs/stable/notes/randomness.html*