### Squeezing, Unsqueezing, and Permuting

* Squeeze - removes all of the `1` dimensions (single dimensions) from a tensor
* Unsqueeze - adds a `1` dimension to a target tensor
* Permute - Returns a view of the tensor with the dimensions swapped(permuted) in a certain way

In [2]:
import torch # type: ignore

# 1. creating a tensor
x = torch.arange(1., 10.)

# copying over code from lesson 9 to match up with the tutorial 
xReshape = x.reshape(1, 9)

xReshape, xReshape.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [3]:
# looking at x with squeeze applied looks like

xReshape.squeeze()
# removes all single dimenstions from a target tensor --> shown here as the tensor changes from 2 square brackets to only 1 square bracket

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [4]:
xReshape.squeeze().shape

# we can see here the the tensor has also been changed to where there is only a single tensor of size nine
# if there was a tensor of [1,1,9], then .squeeze would remove all of the 1 tensors, ending up as 9 only

torch.Size([9])

In [5]:
# visulization of .squeeze()

print(f"Previous Tensor: {xReshape}")
print(f"Previous Tensor Shape: {xReshape.shape}")

print()

print(f"New Tensor: {xReshape.squeeze()}")
print(f"New Tensor Shape: {xReshape.squeeze().shape}")

# as we can the the previous tensor has 2 square brackets, and the new tensor that has been squeezed only has 1 now, as well the shape of the squeezed tensor has also 
# changed

Previous Tensor: tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous Tensor Shape: torch.Size([1, 9])

New Tensor: tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])
New Tensor Shape: torch.Size([9])


In [6]:
# Now testing out .unsqueeze()
# adds a single dimension to a targeted vector at a specific dimension (dim)

xSqueeze = xReshape.squeeze() # creating a new variable to test out how unsqueeze works on a tensor that has been squeezed

xSqueeze.unsqueeze(dim = 0)

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [7]:
# Visulization of .unsqueeze(dim)

print(f"Previous Tensor: {xSqueeze}")
print(f"Previous Tensor Shape: {xSqueeze.shape}")

print()

print(f"New Tensor After Unsqueezing: {xSqueeze.unsqueeze(dim=0)}")
print(f"New Tensor Shape After Unsqueezing: {xSqueeze.unsqueeze(dim=0).shape}")

Previous Tensor: tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous Tensor Shape: torch.Size([9])

New Tensor After Unsqueezing: tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])
New Tensor Shape After Unsqueezing: torch.Size([1, 9])


In [8]:
# Seeing how different dimensions will change the dimensions

# dimensions of 1 will add a new dimension on the first dimension
print(f"New Tensor After Unsqueezing: {xSqueeze.unsqueeze(dim=1)}")
print(f"New Tensor Shape After Unsqueezing: {xSqueeze.unsqueeze(dim=1).shape}")

# the range of dimensions for a tensor with a shape of [9] will be the range of [-2, 1] as the possible dimensions are 0 and 1, and the possible tensors are -2, -1, 0, 1
# since -1 will loop back to 1, and -2 corresponds to 0
# and in this case anything larger than 

New Tensor After Unsqueezing: tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])
New Tensor Shape After Unsqueezing: torch.Size([9, 1])


In [12]:
# torch.permute - will rearrange the dimensions of a specified target tensor in a specific order, and is a view of the data
# parameters: torch.permute(input, dims) --> outputs a new tensor
# imput: tensor
# dims: tuple of int --> your wanted ordering of dimensions

# commonly used with images

xOriginal = torch.rand(size = (244, 244, 3)) # [height, width, colour_channels]

# using permute to change the original tensor to rearragne the axis order so that the colour_channels is the first dimension

# permute changes the order of the original tensor by changing the position of the index in the tensor.permute() function by specifying the order of the indexes in the permute function
xPermute = xOriginal.permute(2, 0, 1) # this shifts 0 -> 2, 1 -> 0, and 2 -> 1

# where the last element(colour_channels) in xOriginal now maps to the first item in xPermute, and the first element(height) in xOriginal maps to the second item, 
# and the second element(width) now maps to the last item in xPermute 


print(f"Previous Shape: {xOriginal.shape}")
print(f"New Shape: {xPermute.shape}") # [colour_channels, width, height]

# the same data are in the two tensors as they share the same data but with a different view and shape
# views in pytorch share the same memory as the original tensor

Previous Shape: torch.Size([244, 244, 3])
New Shape: torch.Size([3, 244, 244])


In [17]:
xOriginal[0, 0, 0] = 11223344
# setting a specific value of the original value to see if xPermute will change with the value

print(f"New shapes value at index [0, 0, 0]: {xPermute[0, 0, 0]}")
# here we can see that changing the original tensor also changes the permuted tensor meaning that the two are connected
# with the changes of one tensor affecting the other

New shapes value at index [0, 0, 0]: 11223344.0
