### Squeezing, Unsqueezing, and Permuting

* Squeeze - removes all of the `1` dimensions (single dimensions) from a tensor
* Unsqueeze - adds a `1` dimension to a target tensor
* Permute - Returns a view of the tensor with the dimensions swapped(permuted) in a certain way


https://youtu.be/Z_ikDlimN6A?t=11666 

In [2]:
import torch

# 1. creating a tensor
x = torch.arange(1., 10.)

# copying over code from lesson 9 to match up with the tutorial 
xReshape = x.reshape(1, 9)

xReshape, xReshape.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [3]:
# looking at x with squeeze applied looks like

xReshape.squeeze()
# removes all single dimenstions from a target tensor --> shown here as the tensor changes from 2 square brackets to only 1 square bracket

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [4]:
xReshape.squeeze().shape

# we can see here the the tensor has also been changed to where there is only a single tensor of size nine
# if there was a tensor of [1,1,9], then .squeeze would remove all of the 1 tensors, ending up as 9 only

torch.Size([9])

In [5]:
# visulization of .squeeze()

print(f"Previous Tensor: {xReshape}")
print(f"Previous Tensor Shape: {xReshape.shape}")

print()

print(f"New Tensor: {xReshape.squeeze()}")
print(f"New Tensor Shape: {xReshape.squeeze().shape}")

# as we can the the previous tensor has 2 square brackets, and the new tensor that has been squeezed only has 1 now, as well the shape of the squeezed tensor has also 
# changed

Previous Tensor: tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous Tensor Shape: torch.Size([1, 9])

New Tensor: tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])
New Tensor Shape: torch.Size([9])


In [12]:
# Now testing out .unsqueeze()
# adds a single dimension to a targeted vector at a specific dimension (dim)

xSqueeze = xReshape.squeeze() # creating a new variable to test out how unsqueeze works on a tensor that has been squeezed

xSqueeze.unsqueeze(dim = 0)

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [11]:
# visulization of .unsqueeze(dim)

print(f"Previous Tensor: {xSqueeze}")
print(f"Previous Tensor Shape: {xSqueeze.shape}")

print()

print(f"New Tensor After Unsqueezing: {xSqueeze.unsqueeze(dim=0)}")
print(f"New Tensor Shape After Unsqueezing: {xSqueeze.unsqueeze(dim=0).shape}")

Previous Tensor: tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous Tensor Shape: torch.Size([9])

New Tensor After Unsqueezing: tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])
New Tensor Shape After Unsqueezing: torch.Size([1, 9])
