### Reshaping, stacking, and viewing tensors

* Reshaping - reshapes a tensor to a desired shape (help with tensor shape problems)
    * View - Returns a view of a input tensor of certain shape, but keeps the same memory/(shows the same tensor but from a different shape)
* Stacking - Combines multiple stacks on top of each other (vstack) or side by side(hstack) (https://pytorch.org/docs/stable/generated/torch.stack.html)

(All work in some way to manipulate the tensor in some way that ends with the tensor shape(or dimension) being changed)

In [1]:
import torch

# 1. creating a tensor
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

1. Reshaping
- Adding an extra dimension
(when reshaping you have to make sure that the new dimensions match the tensor)

In [41]:
xReshape = x.reshape(1,7)

xReshape, xReshape.shape

# here the dimensions of 1,7 are invalid for size 9 as there aren't enough 
# we are trying to squeeze 9 elements into 7 spaces, which doesn't divide equally, so the new shape has to be an factor of the size

RuntimeError: shape '[1, 7]' is invalid for input of size 9

In [42]:
# so instead of the dimensions (1,7), instead the dimensions of (1,9) works as 1 * 9 fits into the total number of elements in the tensor from 1-9
# so any new dimensions that are an multiple of 

xReshape = x.reshape(3,3)

xReshape, xReshape.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [43]:
xReshape = x.reshape(9, 1)

xReshape, xReshape.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [44]:
xReshape = x.reshape(2,9)

# 2 by 9 is invalid as 2 times 9 is greater than than the total elements of the tensor (is double the amonut of elements) is greater than the shape of tensor x

xReshape, xReshape.shape

RuntimeError: shape '[2, 9]' is invalid for input of size 9

2. Changing the view
- Is done by using the pytorch function .view(x, y)
    - with the first parameter x being tied to the number of rows
    - and with the second parameter being tied to the number of cols
- Is similar to reshape: but the use case would be to only visualize the newly changed tensor and not change 

In [45]:
z = x.view(1, 9)
# is similar to reshaping the data --> follows the same 

z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [49]:
#changing z will also change x as the tensor view shares the same memory as the orginal
z[0][0] = 5
z, x

# as shown in the output, when the first element in the z tensor is changed, the first tensor in the x tensor will be also changed to the same value

(tensor([[5., 5., 5., 5., 5., 5., 5., 5., 5.]]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]))

3. Stacking Tensors
- on top of each other: takes a list of tensors, and then concatenates a sequence of said tensors along a new dimension
- all tensors have to be of the same size (all the tensors have to be listed in a [])
- the default is dimension 0

In [52]:
xStack = torch.stack([x, x, x, x], dim = 0)
# creating a stack with 5 x's, and setting the dimension to the default of 0, and stacks vertically

xStack

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [53]:
xStack = torch.stack([x, x, x, x], dim = 0)
# creating a stack with 5 x's, and setting the dimension to 1, and stacks vertically

xStack
# first 0th index is the 0th tensor

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.]])